export const topology = {
  meta: {
    name: 'multi-layer-network-demo',
    version: '1.0.0',
    updatedAt: '2026-02-21T10:30:00+08:00',
  },
  schema: {
    nodeFormula: 'Node(i)={ID,Layer,Location,State,Capacity,Energy}',
    linkFormula: 'Link(i,j)={Bandwidth,Delay,Loss}',
  },
  nodes: [
    {
      id: 'R-001',
      name: '核心路由器 R1',
      type: 'router',
      layer: 'backbone',
      location: {
        geo: { lat: 39.905, lng: 116.401, altitude: 40 },
        logical: { region: 'CN-North', site: 'DC-A', rack: 'R1' },
      },
      state: { online: true, uptimeHours: 4320, lastSeen: '2026-02-21T10:28:00+08:00' },
      capacity: {
        compute: { cpuCores: 32, gpuTflops: 0 },
        storage: { gb: 2048, iops: 12000 },
        cache: { gb: 128 },
      },
      energy: { status: 'grid', batteryLevel: 100, powerW: 520 },
    },
    {
      id: 'R-002',
      name: '汇聚路由器 R2',
      type: 'router',
      layer: 'backbone',
      location: {
        geo: { lat: 39.912, lng: 116.412, altitude: 45 },
        logical: { region: 'CN-North', site: 'DC-B', rack: 'R4' },
      },
      state: { online: true, uptimeHours: 2740, lastSeen: '2026-02-21T10:27:30+08:00' },
      capacity: {
        compute: { cpuCores: 24, gpuTflops: 0 },
        storage: { gb: 1024, iops: 9000 },
        cache: { gb: 96 },
      },
      energy: { status: 'grid', batteryLevel: 100, powerW: 410 },
    },
    {
      id: 'BS-101',
      name: '基站 BS-101',
      type: 'base-station',
      layer: 'access',
      location: {
        geo: { lat: 39.908, lng: 116.423, altitude: 32 },
        logical: { region: 'CN-North', site: 'Zone-1', rack: 'Tower-3' },
      },
      state: { online: true, uptimeHours: 1560, lastSeen: '2026-02-21T10:28:10+08:00' },
      capacity: {
        compute: { cpuCores: 16, gpuTflops: 1.2 },
        storage: { gb: 512, iops: 7000 },
        cache: { gb: 64 },
      },
      energy: { status: 'grid', batteryLevel: 100, powerW: 320 },
    },
    {
      id: 'BS-102',
      name: '基站 BS-102',
      type: 'base-station',
      layer: 'access',
      location: {
        geo: { lat: 39.918, lng: 116.438, altitude: 30 },
        logical: { region: 'CN-North', site: 'Zone-2', rack: 'Tower-1' },
      },
      state: { online: true, uptimeHours: 980, lastSeen: '2026-02-21T10:27:40+08:00' },
      capacity: {
        compute: { cpuCores: 12, gpuTflops: 0.8 },
        storage: { gb: 384, iops: 5200 },
        cache: { gb: 48 },
      },
      energy: { status: 'grid', batteryLevel: 100, powerW: 280 },
    },
    {
      id: 'MN-201',
      name: '自组网节点 MN-201',
      type: 'mesh-node',
      layer: 'mesh',
      location: {
        geo: { lat: 39.914, lng: 116.432, altitude: 120 },
        logical: { region: 'CN-North', site: 'Mesh-A', rack: 'UAV-1' },
      },
      state: { online: true, uptimeHours: 120, lastSeen: '2026-02-21T10:28:35+08:00' },
      capacity: {
        compute: { cpuCores: 8, gpuTflops: 0.2 },
        storage: { gb: 128, iops: 2500 },
        cache: { gb: 16 },
      },
      energy: { status: 'battery', batteryLevel: 72, powerW: 95 },
    },
    {
      id: 'MN-202',
      name: '自组网节点 MN-202',
      type: 'mesh-node',
      layer: 'mesh',
      location: {
        geo: { lat: 39.922, lng: 116.426, altitude: 110 },
        logical: { region: 'CN-North', site: 'Mesh-B', rack: 'UAV-2' },
      },
      state: { online: true, uptimeHours: 98, lastSeen: '2026-02-21T10:28:00+08:00' },
      capacity: {
        compute: { cpuCores: 6, gpuTflops: 0.15 },
        storage: { gb: 96, iops: 2000 },
        cache: { gb: 12 },
      },
      energy: { status: 'battery', batteryLevel: 64, powerW: 88 },
    },
    {
      id: 'UE-301',
      name: '终端 UE-301',
      type: 'terminal',
      layer: 'edge',
      location: {
        geo: { lat: 39.916, lng: 116.445, altitude: 15 },
        logical: { region: 'CN-North', site: 'Campus-1', rack: 'User-A' },
      },
      state: { online: true, uptimeHours: 12, lastSeen: '2026-02-21T10:28:20+08:00' },
      capacity: {
        compute: { cpuCores: 4, gpuTflops: 0.05 },
        storage: { gb: 256, iops: 1200 },
        cache: { gb: 8 },
      },
      energy: { status: 'battery', batteryLevel: 54, powerW: 18 },
    },
    {
      id: 'UE-302',
      name: '终端 UE-302',
      type: 'terminal',
      layer: 'edge',
      location: {
        geo: { lat: 39.926, lng: 116.442, altitude: 18 },
        logical: { region: 'CN-North', site: 'Campus-2', rack: 'User-B' },
      },
      state: { online: false, uptimeHours: 3, lastSeen: '2026-02-21T09:57:00+08:00' },
      capacity: {
        compute: { cpuCores: 6, gpuTflops: 0.1 },
        storage: { gb: 512, iops: 1600 },
        cache: { gb: 12 },
      },
      energy: { status: 'battery', batteryLevel: 22, powerW: 20 },
    },
    {
      id: 'SAT-901',
      name: '低轨卫星 SAT-901',
      type: 'satellite',
      layer: 'backbone',
      location: {
        geo: { lat: 39.94, lng: 116.408, altitude: 550000 },
        logical: { region: 'LEO-Plane-1', site: 'Orbital', rack: 'SAT-901' },
      },
      state: { online: true, uptimeHours: 8600, lastSeen: '2026-02-21T10:28:25+08:00' },
      capacity: {
        compute: { cpuCores: 12, gpuTflops: 0.6 },
        storage: { gb: 256, iops: 4500 },
        cache: { gb: 32 },
      },
      energy: { status: 'solar', batteryLevel: 88, powerW: 240 },
    },
  ],
  links: [
    {
      id: 'L-001',
      from: 'R-001',
      to: 'R-002',
      directed: false,
      type: 'wired',
      bandwidthMbps: 10000,
      utilization: 0.32,
      delayMs: 3,
      lossRate: 0.001,
      availability: 0.999,
      channel: 'fiber',
    },
    {
      id: 'L-002',
      from: 'R-001',
      to: 'BS-101',
      directed: true,
      type: 'wired',
      bandwidthMbps: 2000,
      utilization: 0.48,
      delayMs: 6,
      lossRate: 0.003,
      availability: 0.995,
      channel: 'ethernet',
    },
    {
      id: 'L-003',
      from: 'R-002',
      to: 'BS-102',
      directed: true,
      type: 'wired',
      bandwidthMbps: 2000,
      utilization: 0.52,
      delayMs: 7,
      lossRate: 0.004,
      availability: 0.994,
      channel: 'ethernet',
    },
    {
      id: 'L-004',
      from: 'BS-101',
      to: 'MN-201',
      directed: false,
      type: 'wireless',
      bandwidthMbps: 400,
      utilization: 0.68,
      delayMs: 12,
      lossRate: 0.02,
      snrDb: 22,
      availability: 0.97,
      channel: '5g-nr',
    },
    {
      id: 'L-005',
      from: 'BS-102',
      to: 'MN-202',
      directed: false,
      type: 'wireless',
      bandwidthMbps: 350,
      utilization: 0.74,
      delayMs: 14,
      lossRate: 0.025,
      snrDb: 18,
      availability: 0.965,
      channel: '5g-nr',
    },
    {
      id: 'L-006',
      from: 'MN-201',
      to: 'MN-202',
      directed: false,
      type: 'wireless',
      bandwidthMbps: 180,
      utilization: 0.55,
      delayMs: 18,
      lossRate: 0.03,
      snrDb: 16,
      availability: 0.95,
      channel: '802.11s',
    },
    {
      id: 'L-007',
      from: 'MN-201',
      to: 'UE-301',
      directed: false,
      type: 'wireless',
      bandwidthMbps: 120,
      utilization: 0.82,
      delayMs: 22,
      lossRate: 0.035,
      snrDb: 12,
      availability: 0.94,
      channel: '802.11ax',
    },
    {
      id: 'L-008',
      from: 'MN-202',
      to: 'UE-302',
      directed: false,
      type: 'wireless',
      bandwidthMbps: 110,
      utilization: 0.61,
      delayMs: 24,
      lossRate: 0.04,
      snrDb: 9,
      availability: 0.93,
      channel: '802.11ax',
    },
    {
      id: 'L-009',
      from: 'SAT-901',
      to: 'R-001',
      directed: true,
      type: 'wireless',
      bandwidthMbps: 800,
      utilization: 0.43,
      delayMs: 35,
      lossRate: 0.01,
      snrDb: 20,
      availability: 0.985,
      channel: 'ka-band',
    },
  ],
  accessRelations: [
    {
      id: 'A-001',
      terminalId: 'UE-301',
      meshNodeId: 'MN-201',
      accessNodeId: 'BS-101',
      backhaulLinkId: 'L-002',
      notes: '终端 UE-301 通过 MN-201 接入 BS-101 上行到骨干网。',
    },
    {
      id: 'A-002',
      terminalId: 'UE-302',
      meshNodeId: 'MN-202',
      accessNodeId: 'BS-102',
      backhaulLinkId: 'L-003',
      notes: '终端 UE-302 通过 MN-202 接入 BS-102，上行到骨干网。',
    },
  ],
  api: {
    rest: {
      basePath: '/api/v1',
      endpoints: [
        {
          method: 'GET',
          path: '/topology',
          description: '获取当前拓扑快照',
          responseShape: {
            nodes: 'Node[]',
            links: 'Link[]',
            accessRelations: 'AccessRelation[]',
          },
        },
        {
          method: 'GET',
          path: '/nodes/:id',
          description: '按节点 ID 查询属性与状态',
          responseShape: { node: 'Node' },
        },
        {
          method: 'GET',
          path: '/links/:id',
          description: '按链路 ID 查询链路属性',
          responseShape: { link: 'Link' },
        },
        {
          method: 'PATCH',
          path: '/nodes/:id/state',
          description: '更新节点在线/能耗状态',
          requestShape: { online: 'boolean', energy: 'Energy' },
        },
      ],
    },
    websocket: {
      url: 'wss://example.com/topology',
      topics: [
        {
          topic: 'node.state.changed',
          payloadShape: { id: 'string', state: 'State', energy: 'Energy' },
        },
        {
          topic: 'link.quality.changed',
          payloadShape: { id: 'string', delayMs: 'number', lossRate: 'number' },
        },
        {
          topic: 'access.relation.changed',
          payloadShape: { id: 'string', terminalId: 'string', meshNodeId: 'string' },
        },
      ],
    },
  },
};
